export const blogs = [
	{
		id: 14,
		title: "Environment Variables in Flutter Apps",
		href: "https://medium.com/stackademic/environment-variables-in-flutter-apps-db3d07999731",
		description: "Secure and simplify your flutter app configuration with best practices and advanced tools.",
		date: "Aug 24, 2024",
		datetime: "2024-08-24",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Stackademic",
			href: "https://blog.stackademic.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 14,
		title: "Introducing Xarvis CLI: Generate Production Ready Starter Template",
		href: "https://blog.stackademic.com/introducing-xarvis-cli-generate-production-ready-starter-template-a996da4c49c3",
		description:
			"Xarvis CLI is a powerful command-line interface tool that allows developers to easily generate production-ready starter templates for their projects.",
		date: "Oct 17, 2023",
		datetime: "2023-10-17",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Stackademic",
			href: "https://blog.stackademic.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 13,
		title: "How to Extract Metadata from a Web URL in Flutter",
		href: "https://blog.stackademic.com/how-to-extract-metadata-from-url-in-flutter-46d03df1ae7b",
		description:
			"Welcome to this article, where we'll explore how to make your apps smarter by extracting useful information from web links.",
		date: "Sep 9, 2023",
		datetime: "2023-09-09",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Stackademic",
			href: "https://blog.stackademic.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 12,
		title: "Demystifying Backend Development: Why It's Essential for Successful Projects",
		href: "https://thecodexhub.hashnode.dev/demystifying-backend-development",
		description:
			"Explore essential backend aspects - data, security, scalability, APIs, logic, and more - and why Flutter devs should embrace it.",
		date: "Aug 31, 2023",
		datetime: "2023-08-31",
		channel: { name: "Hashnode", href: "https://thecodexhub.hashnode.dev" },
		author: {
			name: "Sandip Pramanik",
			publisher: "",
			href: "",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 11,
		title: "Build Reactive Apps in Flutter with Streams and Bloc",
		href: "https://blog.stackademic.com/build-reactive-apps-in-flutter-with-streams-and-bloc-b26dac1e7910",
		description: "Learn how to use Streams and Bloc to build a reactive stopwatch app in Flutter",
		date: "Aug 27, 2023",
		datetime: "2023-08-27",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Stackademic",
			href: "https://blog.stackademic.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 10,
		title: "Dart Frog - Fast & Minimalistic Backend Framework for Dart",
		href: "https://towardsdev.com/dart-frog-fast-minimalistic-backend-framework-for-dart-fcfca966c976",
		description: "Explore the Dart Frog framework with an example Books Directory application",
		date: "Sep 9, 2022",
		datetime: "2022-09-09",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 9,
		title: "Flutter and ObjectBox - High-Performance NoSQL Database",
		href: "https://towardsdev.com/flutter-and-objectbox-high-performance-nosql-database-e540b4ae91ee",
		description:
			"Persisting data locally or remotely on the server is one of the fundamental requirements of any mobile application development process. Choosing a suitable database to work with, can sometimes be tricky.",
		date: "Aug 28, 2022",
		datetime: "2022-08-28",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 8,
		title: "Slivers in Flutter - Efficient and Fancy Scrolling Experience",
		href: "https://towardsdev.com/slivers-in-flutter-efficient-and-fancy-scrolling-experience-9a3f5b370666",
		description:
			"Learn one of the scariest topics in Flutter - what is sliver and how to make use of it to build an elegant scroll view",
		date: "Jul 28, 2022",
		datetime: "2022-07-28",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 7,
		title: "Declarative Routing - Flutter Navigator 2.0 with GoRouter",
		href: "https://towardsdev.com/flutter-navigator-2-0-with-gorouter-fb2dd998e40e",
		description: "Learn about the declarative routing mechanism in Flutter using the go_router package",
		date: "Jul 16, 2022",
		datetime: "2022-07-16",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 6,
		title: "TextInputFormatter in Flutter - Format User’s Input on-the-fly",
		href: "https://towardsdev.com/textinputformatter-in-flutter-format-users-input-on-the-fly-71510af8a44c",
		description:
			"Learn how to format user input in real-time for a text field, minimize errors and improve user experience",
		date: "Jun 26, 2022",
		datetime: "2022-06-26",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 5,
		title: "Multi-Step Form with Flutter Bloc and Stepper Widget",
		href: "https://towardsdev.com/multi-step-form-with-flutter-bloc-and-stepper-widget-8d65b611cce1",
		description:
			"Learn how to build a multi-step form flow and how to use bloc to effectively isolate the presentation layer from the business logic layer",
		date: "Jun 14, 2022",
		datetime: "2022-06-14",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 4,
		title: "Dio Package in Flutter - HTTP Requests and Interceptors",
		href: "https://towardsdev.com/dio-package-in-flutter-http-requests-and-interceptors-2c3d6ef3e9a3",
		description:
			"Learn how to use Flutter Dio package to make http requests, deal with interceptors and take care of unexpected server responses.",
		date: "May 31, 2022",
		datetime: "2022-05-31",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 3,
		title: "Flutter SQLite Database - Persist Data with sqflite",
		href: "https://towardsdev.com/flutter-sqlite-database-persist-data-with-sqflite-74283c51b9a2",
		description: "Learn how to use sqflite to store complex relational data locally in Flutter apps",
		date: "Dec 21, 2021",
		datetime: "2021-12-21",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "Towards Dev",
			href: "https://towardsdev.com/",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 2,
		title: "Local Notifications in Flutter - Notify Users with Minimal Effort",
		href: "https://medium.com/@thecodexhub/local-notifications-in-flutter-5e1e871a241c",
		description:
			"Learn how to implement local notifications into both Android and iOS using flutter_local_notifications plugin",
		date: "Nov 17, 2021",
		datetime: "2021-11-17",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "",
			href: "#",
			imageUrl: "./icon-512x512.png",
		},
	},
	{
		id: 1,
		title: "Flutter Localization - Internationalization with JSON",
		href: "https://medium.com/@thecodexhub/flutter-localization-internationalization-with-json-3ade47abca3f",
		description: "Learn how to track device locale and easily Localize and Internationalize your Flutter app",
		date: "Nov 9, 2021",
		datetime: "2021-11-09",
		channel: { name: "Medium", href: "https://medium.com/@thecodexhub" },
		author: {
			name: "Sandip Pramanik",
			publisher: "",
			href: "#",
			imageUrl: "./icon-512x512.png",
		},
	},
];
